ingress:
  # allows you to specify custom hosts
  customHosts:
    # specify your ngrok custom domain here
    # such as
    # hook: "https://d533-160-158-126-38.ngrok-free.app"
    # so that webhooks from, say, github.com, will work to your local laptop
    hook: "http://9lgukk-ip-196-228-28-45.tunnelmole.net"

kaniko:
  # lets support insecure docker registries so that we
  # can use the local docker-registry chart
  flags: "--insecure"
